API_TITLE: BUTTON SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# MQTT CONFIGURATION
MQTT_BROKER_ADDRESS: 192.168.1.20 # rpi_box
MQTT_USERNAME: rpi_buttons
MQTT_PASSWORD: lamp
MQTT_QOS: 1
MQTT_RECONNECTION_TIMEOUT_IN_SEG: 1
MQTT_MAX_RECONNECTION_ATTEMPS: 3
MQTT_MSG_PUBLISH_TIMEOUT_IN_SECS: 5

# Thread configuration
THREAD_SERIAL_INTERFACE: /dev/ttyACM0
THREAD_SERIAL_SPEED: 115200
THREAD_UDP_PORT: 45
MQTT_THREAD_NETWORK_INFO_TOPIC: thread/network_info
THREAD_MESSAGES: server_button/server/config/thread-messages.yml

# Peripherals configuration
PERIPHERALS_BUTTONS_MATRIX_L1: 21
PERIPHERALS_BUTTONS_MATRIX_L2: 20
PERIPHERALS_BUTTONS_MATRIX_C1: 16
PERIPHERALS_BUTTONS_MATRIX_C2: 12
BUTTONS_STATUS_POLL_PERIOD_IN_SECS: 0.1
MQTT_COMMAND_NOTIFICATION_TOPIC: command/button #TODO: review

# Wifi connection status
WIFI_CONNECTION_STATUS_POLL_PERIOD_IN_SECS: 1
TEST_CONNETION_IP: 192.168.1.1
